### ISSUE TITLE
Mine/Optimize Software Engineering Assessments

### ISSUE THREAD

**Issue by shervine** [menchblogs/platform#1950]
@grumo As per our discussions, this is the very first step that I will be taking to have a better understanding of our mining process so I can build #1435 in the most effective way.

I will log my work here:

https://docs.google.com/spreadsheets/d/1enBnYSRN6QBTQybrvhAzVmF_nUCmZPxqtTmZ3KOdjzM/edit#gid=2143901712

And will also list all videos to this issue while logging my time using EverHour so we can get a realistic estimate of how long it takes to mine 1 hour of video content.

**Comment by shervine** [comment]
Will continue this when triple is ready

**Comment by grumo** [comment]
All Pluralsight Assessments: https://app.pluralsight.com/score
- HTML 5: https://app.pluralsight.com/score/skill-assessment/html5/intro?context=paths&path_type=skill&path_url=html5#/preassessment
- Javascript: https://app.pluralsight.com/score/skill-assessment/javascript/summary-review?context=paths&path_type=skill&path_url=javascript
-

**Comment by shervine** [comment]
@grumo Based on our talk here are the pending mining tasks for our MVP launch:

- [ ] Group self-assessment branch
- [ ] Assign Assessment Marks to self-assessment tree
- [ ] Add Intent Notes and complete the [Learn more about Mench's free services](https://mench.com/intents/9819) tree so we can inform students about our services
- [ ] Add [Mench Assessment Score Webhook](https://mench.com/entities/6108) to newly added programming assessments. It's currently assigned to 10 assessments.

**Comment by grumo** [comment]
LinkedIn has their own multiple-choice assessments: https://www.linkedin.com/in/miguelvancouver/detail/assessments/assessment-hub/quizzes/
This means employers can search for candidates that have proven their skills.
This eats into our value proposition for using Mench for candidate assessment.
Our point of differentiation would be to convince Companies our assessment tech is more engaging and customizable. There is no customization on LinkedIn as far as I can see.

**Comment by shervine** [comment]
@grumo Yes, plus we will educate each candidate so they learn more about the company, which is great branding and promotion for them even if they never get hired.

By using Mench they will transform their candidate funnel (which is very costly to filter) into a marketing funnel where they get to sell themselves and do a super personalized assessment (technical and culture fit too!), and by the end of this funnel they will get matches candidates based on many criteria.

This is pretty different that anything out there as its a unique mix of LinkedIn, Indeed, TripleByte, The Muse and Wikipedia.

**Comment by shervine** [comment]
@grumo Based on the TripleByte's top programming languages/frameworks and the [ones we have added so far](https://mench.com/intents/10410), we're missing assessments for these:

- [ ] Clojure
- [ ] Go
- [ ] Kotlin
- [ ] C (We have C++ and C# only)
- [ ] Objective-C
- [ ] Scala
- [ ] Swift
- [ ] Ruby (Language)
- [ ] Ruby on Rails (Framework)
