### ISSUE TITLE
Mine Personality Tests

### ISSUE THREAD

**Issue by grumo** [menchblogs/platform#2363]
- [ ] Narcissistic Personality test: https://openpsychometrics.org/printable/narcissistic-personality-inventory.pdf
- [ ] https://www.123test.com/ (they charge companies $8-16 per user -> https://www.123test.com/tickets/)
- [x] https://www.psytoolkit.org/survey-library/zkpq-50-cc.html#refs ([on Mench](https://mench.com/intents/11170#intentnotes-11170))
- [x] Asperger and Autism tests: https://www.autismresearchcentre.com/arc_tests
- [x] https://psychology-tools.com/test/empathy-quotient
- [ ] https://www.gallupstrengthscenter.com/home/en-us/strengthsfinder

**Comment by shervine** [comment]
Nice!

**Comment by grumo** [comment]
Let's wait for input from companies as to what assessments they prefer. Also, I checked the top 10 personality assessments and most require to pay to take them. After paying, we'd still need to reverse engineer them the same way I did with https://www.16personalities.com/

**Comment by shervine** [comment]
@grumo Yes I agree, these are useful but we need more perspective on how to integrate them with that our partner employers are looking for

**Comment by shervine** [comment]
@grumo I reviewed and added the intention to [Determine your Emotional Intelligence (EI)](https://mench.com/intents/11476) to my Action Plan and I think its not good. The questions are very vague/generic and it does not feel like an indirect assessment at all. I believe there are personality tests that are better designed, I just think this particular one was pretty bad.

**Comment by shervine** [comment]
@grumo what was the inspiration behind adding this one?
