### ISSUE TITLE
Fixed System Intentions V1

### ISSUE THREAD

**Issue by shervine** [menchblogs/platform#2401]
There are some intents that all users must take when they first join Mench. It does not make sense to add these intents to the beginning of each intent tree, because then they have to be everywhere! Instead, similar to [Featured Intentions](https://mench.com/intents/8469), we can create a new type of intent parent called [Required Intentions](https://mench.com/intents/11665) which would always be added to all new user's Action Plans when they first join Mench, giving them the option to skip as many steps as they want.

I have currently added some intentions which I think need to belong to [Require Intentions](https://mench.com/intents/11665).

@grumo Thoughts?

TODO

- [ ] Enable students to Rate their Experience once done #2013

**Comment by grumo** [comment]
@shervine It would work as long as the required intentions are short, generic, and only delivered once per user.
