### ISSUE TITLE
Entity tagging after intent completion

### ISSUE THREAD

**Issue by grumo** [menchblogs/platform#2453]
@shervine This would be a very powerful user categorization feature. 
I noticed is a common feature on chatbot builders for user categorization and routing.

How it would work:
- A new entity called "Tags" would be created
- Miner clicks on an intent's cog wheel
- There is a new field called "Tags" 
- Miner types one or more tags (entity link values) to be added to user once intent is completed
- If tag doesn't exist then it would be auto-created

Thoughts?

TODO

- [x] Auto remove sibling entities if tagged entity is the granchild of [Single Selectable](https://mench.com/entities/6204)
- [ ] Check in-advance if there is a current link between the user and all tagged entities and if so, check to see if the value stored in those link contents match the entity input requirement

**Comment by shervine** [comment]
@grumo We just talked about this and its a great idea. The goal is to link entities when users complete an intention. To do so, we would allow each intent to have a "Entity Link Reference" which the miner can set. The miner can also set a "Link Content Value" and when the user completes the intent, the entity would be linked as the user parent and the link content value would be stored, if any.

**Comment by shervine** [comment]
@grumo Added this to intent notes and will wire it in later on...
